# Generated by Django 5.1.7 on 2025-03-11 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerentes', '0001_initial'),
        ('posto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posto',
            name='gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerentes.gerente', verbose_name='Gerente'),
        ),
    ]
