# Generated by Django 5.1.7 on 2025-03-11 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0001_initial'),
        ('vouchers', '0002_voucher_data_voucher_embarcador_voucher_motorista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='qrcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='rota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rota.rota'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=6),
        ),
    ]
