# Generated by Django 5.1.7 on 2025-03-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_voucher_qrcode_image_voucher_rota_voucher_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='qrcode',
        ),
    ]
